
if(!window.QC){window.QC={};}
$.extend(window.QC,{utils:{}});(function($){$.extend(window.QC.utils,{verifyFlag:false,'Reg':{domain:/^http(s)?:\/\/[\w-]+(\.[\w-]+)+\/?$/i,ip:/^http(s)?:\/\/\d+(\.\d+){3}$/,ipCallback:/\b\d+(\.\d+){3}\b/,callback:/^([\w-]+(\.[\w-]+)+)+(\s*;\s*[\w-]+(\.[\w-]+)+)*$/,url:/^http(s)*:\/\/[0-9A-Za-z\-_]+(\.[0-9A-Za-z\-_]+)+(\/[0-9A-Za-z\-_\.%\?&=]+)*\/?$/},getCookie:function(name){var r=new RegExp("(?:^|;+|\\s+)"+name+"=([^;]*)");var m=window.document.cookie.match(r);return(!m?"":m[1]);},getUin:function(){if(typeof(_uin)=='undefined'){_uin=this.getCookie('uin').replace(/^[o0]+/i,'');}
return _uin;},getUrlParam:function(name){var reg=new RegExp("(^|&)"+name+"=([^&]*)(&|$)");var r=window.location.search.substr(1).match(reg);if(r!=null)return unescape(r[2]);return null;},formatDate:function(timestamp){if(!timestamp)return'';if(timestamp.toString().length<13){timestamp*=1000;}
var date=new Date(timestamp),year,month,day;year=date.getFullYear();month=date.getMonth()+1;day=date.getDate();return year+'-'+((month<10)?'0':'')+month+'-'+((day<10)?'0':'')+day;},detachLogin:function(code){if(!this.getUin()||code==100000){window.location="http://connect.qq.com/manage/login";}else if(code==200007){window.location="http://connect.qq.com/manage/index";}},showTip:function(e,content){if($.browser.msie||$.browser.mozilla){var x=e.clientX+document.documentElement.scrollLeft-document.documentElement.clientLeft-20,y=e.clientY+document.documentElement.scrollTop-document.documentElement.clientTop+20;}else{var x=e.clientX+document.body.scrollLeft-document.body.clientLeft-20,y=e.clientY+document.body.scrollTop-document.body.clientTop+20;}
$(".bubble_query").css("top",y);$(".bubble_query").css("left",x);$(".bubble_query").css("z-index",20000);$(".bubble_i").html(content);$(".bubble_query").show();if($.browser.msie&&$.browser.version=='6.0'&&$(e.target).parent().attr("for")=="provider"){$('.bubble_query').bgiframe({width:$('.bubble_query').width(),height:50});}},hideTip:function(){$(".bubble_query").hide();},createMetaContent:function(domainUrl){if(!domainUrl){return false;}
var uin=this.getUin(),i,ret="";uin=uin.toString();if(uin.length<=domainUrl.length){for(i=0;i<uin.length;i++){ret+=((domainUrl.charCodeAt(i)^uin.charCodeAt(i))&7);}
for(i=uin.length;i<domainUrl.length;i++){ret+=(domainUrl.charCodeAt(i)^0)&7;}}
else{for(i=0;i<domainUrl.length;i++){ret+=((domainUrl.charCodeAt(i)^uin.charCodeAt(i))&7);}
for(i=domainUrl.length;i<uin.length;i++){ret+=(uin.charCodeAt(i)^0)&7;}}
return ret;},verifyBlackUrl:function(){QC.CGI.checkBlackUrl({data:{url:$("#siteUrl").val()},onSuccess:function(res){if(res.retcode==103111){$(".appHomeTips").text("经安全系统检测，该网站地址非法");}}});},verifyUrl:function(){var self=this,flag=false;var Reg={domain:/^http(s)?:\/\/[\w-]+(\.[\w-]+)+\/?$/i,ip:/^http(s)?:\/\/\d+(\.\d+){3}$/,ipCallback:/\b\d+(\.\d+){3}\b/,callback:/^([\w-]+(\.[\w-]+)+)+(\s*;\s*[\w-]+(\.[\w-]+)+)*$/,url:/^http(s)*:\/\/[0-9A-Za-z\-_]+(\.[0-9A-Za-z\-_]+)+(\/[0-9A-Za-z\-_\.%\?&=]+)*\/?$/};var appurl=$("#siteUrl").val(),reg=Reg.url,ipReg=Reg.ip,tip="";if(!appurl.length){tip="请填写网站地址";}else if(!reg.test(appurl)){tip="网站地址不规范";}else if(ipReg.test(appurl)){tip="网站：请填写网站的地址，不支持IP地址注册。";}else{flag=true;}
if(!flag){$(".appHomeTips").text(tip);}
return flag;},verifyCallback:function(){if(!$(".call_address").val()){$(".siteCallbackTips").text("请填写回调地址");return false;}else{var input=$(".call_address");var callbackUrl=input.val().match(/[^\s;；]+/g)||[];input.val(callbackUrl.join(";"));var regExp=/^https?:\/\/([\w-]+\.)+[\w-]+(\/[^?#]*)?$/;for(var i=0;i<callbackUrl.length;i++){if(!regExp.test(callbackUrl[i])){$(".siteCallbackTips").text("填写不规范");return false;}}}
return true;},bindCommonFormEvent:function(action){var self=this;$("#siteUrl").focusout(this.verifyUrl);$(".verify-btn").hover(function(){if(self.verifyUrl()){if(self.verifyFlag){QC.CGI.checkBlackUrl({data:{url:$("#siteUrl").val()},onSuccess:function(res){if(res.retcode==0){$("#p_metaContent").text('<meta property="qc:admins" content="'+self.createMetaContent($("#siteUrl").val())+'" />');$(".verify-box").css('visibility','visible');self.verifyFlag=false;}else if(res.retcode==103111){$(".appHomeTips").text("经安全系统检测，该网站地址非法");}}});}else{$("#p_metaContent").text('<meta property="qc:admins" content="'+self.createMetaContent($("#siteUrl").val())+'" />');$(".verify-box").css('visibility','visible');}}else{$(".verify-box").css('visibility','hidden');}},function(){$(".verify-box").css('visibility','hidden');});$(".verify-start").bind("click",function(){var data={url:$.trim($("#siteUrl").val())||''};QC.CGI.verifySiteUrl({data:data,onSuccess:function(res){if(res&&res.retcode==0){$(".verify-tips").text('已通过验证');$(".verify-tips").removeClass("verify-err");$(".verify-tips").addClass("verify-ok");if(action=='create'){QC.MesBox.setContentWidth(650);if($.browser.msie&&$.browser.version=='6.0'){$(".msgBoxHeader").css("width","720px");}}else{QC.MesBox.setContentWidth(600);}
$(".verify-ok").show();QC.createAppMgr&&(QC.createAppMgr.global.isSiteUrlVerified=true);QC.appDetail&&(QC.appDetail.global.isSiteUrlVerified=true);QC.appInfo&&(QC.appInfo.global.isSiteUrlVerified=true);$(".verify-ok-tips").fadeIn();window.setTimeout(function(){$(".verify-ok-tips").fadeOut();},2000);}else{$(".verify-tips").text('未通过验证');$(".verify-tips").removeClass("verify-ok");$(".verify-tips").addClass("verify-err");if(action=='create'){QC.MesBox.setContentWidth(650);}else{QC.MesBox.setContentWidth(600);}
if($.browser.msie&&$.browser.version=='6.0'){$(".msgBoxHeader").css("width","720px");}
$(".verify-tips").show();QC.createAppMgr&&(QC.createAppMgr.global.isSiteUrlVerified=false);QC.appInfo&&(QC.appInfo.global.isSiteUrlVerified=false);$(".verify-err-tips").text('验证失败('+res.retcode+')');$(".verify-err-tips").fadeIn();window.setTimeout(function(){$(".verify-err-tips").fadeOut();},2000);}}});});$(".call_address").focusout(this.verifyCallback);$(".call_address").bind("focusin",function(){$(".siteCallbackTips").text("");});$("#siteUrl").bind("keydown",function(){$(".appHomeTips").text("");$(".verify-tips").text("");$(".verify-tips").hide();if(action=='create'){QC.MesBox.setContentWidth(590);}else{QC.MesBox.setContentWidth(500);}
self.verifyFlag=true;});$(".appname").bind("focusin",function(){if($('.appname').parsley('validate')){$(".appnameTips").text("");}});$(".appinfo").bind("focusin",function(){if($('.appinfo').parsley('validate')){$(".appinfoTips").text("");$(".remarkTips").text("");}});$(".provider").bind("focusin",function(){if($('.provider').parsley('validate')){$(".providerTips").text("");}});},encodeHtml:function(sStr){return String(sStr).replace(/[&'"<>\/\\\-\x00-\x09\x0b-\x0c\x1f\x80-\xff]/g,function(r){return"&#"+r.charCodeAt(0)+";";}).replace(/ /g,"&nbsp;").replace(/\r\n/g,"<br />").replace(/\n/g,"<br />").replace(/\r/g,"<br />");}});})(jQuery);/*  |xGv00|adeab5ce985157c9e3ca02f7a411819e */