;(function(){jQuery.cookie=function(key,value,options){if(arguments.length>1&&(value===null||typeof value!=="object")){options=jQuery.extend({},options);if(value===null){options.expires=-1;}
if(typeof options.expires==='number'){var days=options.expires,t=options.expires=new Date();t.setDate(t.getDate()+days);}
return(document.cookie=[encodeURIComponent(key),'=',options.raw?String(value):encodeURIComponent(String(value)),options.expires?'; expires='+options.expires.toUTCString():'',options.path?'; path='+options.path:'',options.domain?'; domain='+options.domain:'',options.secure?'; secure':''].join(''));}
options=value||{};var result,decode=options.raw?function(s){return s;}:decodeURIComponent;return(result=new RegExp('(?:^|; )'+encodeURIComponent(key)+'=([^;]*)').exec(document.cookie))?decode(result[1]):null;};})();;(function(window,$){var instance=null;var Mask=function(){if(instance){return instance;}else{instance=init();return instance;}};var init=function(){var tpl='<div id="mask" class="mask"></div>';var el=$(tpl);var isIE6=($.browser['msie']&&$.browser.version<7)?true:false;var getClientWH=function(){var docEl=document.documentElement;var bodyWidth=Math.max(docEl.scrollWidth,docEl.clientWidth),bodyHeight=Math.max(docEl.scrollHeight,docEl.scrollHeight);return{w:bodyWidth,h:bodyHeight}};var $body=$(document.body);var $html=$(document.getElementsByTagName("html")[0]);$body.append(el);var show=function(type){$body.addClass("overflow_hidden");$html.addClass("overflow_hidden");if(isIE6){var wh=getClientWH();el.width(wh.w).height(wh.h);$(window).bind("resize",function(){var wh=getClientWH();el.width(wh.w).height(wh.h);});}
el.show();};var hide=function(){$body.removeClass("overflow_hidden");$html.removeClass("overflow_hidden");el.hide();$(window).unbind("resize");};return{show:show,hide:hide};}
$.Mask=Mask;})(window,jQuery);document.domain='qq.com';if(!window.QC){window.QC={};}
$(function(){$.extend(window.QC,{LoginMgr:{callbackQueue:[],checkLogin:function(){return!!$.cookie('skey');},logout:function(){$.cookie('skey',null,{path:'/',domain:'qq.com',secure:true});if(window.location.href.indexOf('/manage/')!=-1){window.location="http://connect.qq.com/manage/login";}else{location.reload(true);}},login:function(callback){var loginHTML='<div id="login_div" style="position:fixed;width:490px;height:328px;top:50%;left:50%;padding:0;margin:0;margin-top:-164px;margin-left:-245px;z-index:1001;_position:absolute;_margin:0" align="center"><iframe id="login_frame" name="login_frame" frameborder="0" scrolling="auto" width="100%" height="100%" src=""></iframe></div>';if(!this.el){this.el=$(loginHTML);$('body').append(this.el);var href='http://ui.ptlogin2.qq.com/cgi-bin/login?style=11&appid=716027613&target=self&s_url='+escape('http://connect.qq.com/success.html');if(window.location.pathname.indexOf("auth_manager")!=-1){href+="&hide_close_icon=1";}
$('#login_frame').attr("src",href);}
var isIE6=($.browser['msie']&&$.browser['version']<8)||document.documentMode==7;if(isIE6){this.el.setCenter();}
this.el.show();if(!this.mask){this.mask=$.Mask();}
this.mask.show();if(callback){this.callback=callback;}
window.loginCallback=function(){$.getJSON('http://cgi.connect.qq.com/qqconnectopen/openapi/get_nick?callback=?',{retype:2},function(json){if(json.retcode==0){QC.LoginMgr.defaultCallback(json.result);var callbackQueue=QC.LoginMgr.callbackQueue;if(callbackQueue.length){for(var i=0;i<callbackQueue.length;i++){callbackQueue[i]();}}}});QC.LoginMgr.mask.hide();QC.LoginMgr.el.hide();QC.LoginMgr.callback&&QC.LoginMgr.callback();}},defaultCallback:function(result){var nick=result.nick,uin=parseInt($.cookie('uin').slice(1),10);$('#login').unbind().text(nick);$("#subNav").show();$("#userInfo").hover(function(){$("#subNav").hide();$("#subNav_hover").show();$("#personal_list").addClass('opened');},function(){$("#subNav").show();$("#subNav_hover").hide();$("#personal_list").removeClass('opened');});$('#logout').click(function(){QC.LoginMgr.logout();return false;});$("#nav_manage a").attr("href","/manage/index");},getUin:function(){return $.cookie('uin').replace(/^[o0]+/i,'');},addCallback:function(callbackFn){this.callbackQueue.push(callbackFn);}}});});function ptlogin2_onClose(){if(location.pathname.indexOf('auth_manager')!=-1){QC.LoginMgr.login();}else{QC.LoginMgr.el.hide();QC.LoginMgr.mask.hide();}}
function ptlogin2_onResize(width,height){if(QC.LoginMgr.el){QC.LoginMgr.el.hide().css({'width':width+'px','height':height+'px','marginTop':-height/2+'px','marginLeft':-width/2+'px'}).show();}}
var QC_Alias=QC;$(function(){var path=window.location.pathname;if(path.indexOf('manager')!=-1){path='';}else if(path.indexOf('manage')!=-1){path='manage';}else if(path.indexOf('login')!=-1){path='qqlogin';}else if(path.indexOf('intro/')!=-1){path='intro';}else{path='index';}
var navDom=document.getElementById("nav_"+path);navDom&&(navDom.className='current');if(QC.LoginMgr.checkLogin()){$.getJSON('http://cgi.connect.qq.com/qqconnectopen/openapi/get_nick?callback=?',{retype:2},function(json){if(json.retcode==0){try{QC.LoginMgr.defaultCallback(json.result);}catch(e){QC_Alias.LoginMgr.defaultCallback(json.result);}}else{$("#login").click(function(){QC.LoginMgr.login();});}});}else{$('#login').click(function(){QC.LoginMgr.login();});}
$.getScript("http://pub.idqqimg.com/pc/misc/connect/website/index_configs.js",function(data){if(cdnData&&cdnData.tips){$("#yellowTipText").html(cdnData.tips);$("#yellowTip").show();$("#yellowTipClose").click(function(){$("#yellowTip").remove();});}});var Tool={getViewportWidth:function(){if(window.innerWidth)return window.innerWidth;else if(document.documentElement&&document.documentElement.clientWidth)return document.documentElement.clientWidth;else if(document.body.clientWidth)return document.body.clientWidth;},getViewportHeight:function(){if(window.innerHeight)return window.innerHeight;else if(document.documentElement&&document.documentElement.clientHeight)return document.documentElement.clientHeight;else if(document.body.clientHeight)return document.body.clientHeight;},getHorizontalScroll:function(){if(window.pageXOffset)return window.pageXOffset?window.pageXOffset:0;else if(document.documentElement&&document.documentElement.scrollLeft)return document.documentElement.scrollLeft?document.documentElement.scrollLeft:0;else if(document.body.scrollLeft)return document.body.scrollLeft?document.body.scrollLeft:0;},getVerticalScroll:function(){if(window.pageYOffset)return window.pageYOffset?window.pageYOffset:0;else if(document.documentElement&&document.documentElement.scrollTop)return document.documentElement.scrollTop?document.documentElement.scrollTop:0;else if(document.body.scrollTop)return document.body.scrollTop?document.body.scrollTop:0;}};$.fn.setCenter=function(param){var viewWidth,viewHeight,scrollLeft,scrollTop,elWidth,elHeight,posTop,posLeft;var el=$(this);elWidth=el.width();elHeight=el.height();viewWidth=Tool.getViewportWidth();viewHeight=Tool.getViewportHeight();scrollLeft=Tool.getHorizontalScroll();scrollTop=Tool.getVerticalScroll();posTop=($.browser.msie&&$.browser.version<'7.0'&&scrollTop?scrollTop:0)+(viewHeight-elHeight)/2;posLeft=(scrollLeft?scrollLeft:0)+(viewWidth-elWidth)/2;el.css({"top":posTop+"px"});if(param&&param.ingoreWidth){el.css({"top":posTop+60+"px"});}else{el.css({"left":posLeft+"px"});}
el.show();return el;};QC.reportBNL=function(id,obj){var timestamp=+new Date();if(!QC.img){QC.img=document.createElement('img');}
obj=obj||0;QC.img.src='http://cgi.connect.qq.com/report/report?strValue='+obj+'&nValue='+id+'&tag=0&t='+timestamp;}
QC.getQueryParam=function(key){url=location.search.substring(1);url=url.split('&');var temp;for(var i=url.length;i--;){temp=url[i].split('=');if(temp[0]==key){return temp[1];}}
return null;}});/*  |xGv00|c5dd9714493277750241eb538cdb3bf6 */